# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClientRequest.proto',
  package='ClientRequest',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x43lientRequest.proto\x12\rClientRequest\"Y\n\rClientRequest\x12\x12\n\nactionType\x18\x01 \x01(\x05\x12\x10\n\x08\x61\x63tionId\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x63\x63tId\x18\x03 \x01(\t\x12\x12\n\nrequestAmt\x18\x04 \x01(\x05\"W\n\x0e\x43lientResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tionId\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x63\x63tId\x18\x03 \x01(\t\x12\x13\n\x0bresponseAmt\x18\x04 \x01(\x05\x32\xeb\x01\n\x07Greeter\x12K\n\nGetBalance\x12\x1c.ClientRequest.ClientRequest\x1a\x1d.ClientRequest.ClientResponse\"\x00\x12I\n\x08Withdraw\x12\x1c.ClientRequest.ClientRequest\x1a\x1d.ClientRequest.ClientResponse\"\x00\x12H\n\x07\x44\x65posit\x12\x1c.ClientRequest.ClientRequest\x1a\x1d.ClientRequest.ClientResponse\"\x00\x42\x33\n\x1cio.grpc.comp5325.assignment4B\x0c\x43OMP5325BankP\x01\xa2\x02\x02\x43Rb\x06proto3')
)




_CLIENTREQUEST = _descriptor.Descriptor(
  name='ClientRequest',
  full_name='ClientRequest.ClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionType', full_name='ClientRequest.ClientRequest.actionType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionId', full_name='ClientRequest.ClientRequest.actionId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acctId', full_name='ClientRequest.ClientRequest.acctId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestAmt', full_name='ClientRequest.ClientRequest.requestAmt', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=127,
)


_CLIENTRESPONSE = _descriptor.Descriptor(
  name='ClientResponse',
  full_name='ClientRequest.ClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ClientRequest.ClientResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionId', full_name='ClientRequest.ClientResponse.actionId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acctId', full_name='ClientRequest.ClientResponse.acctId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseAmt', full_name='ClientRequest.ClientResponse.responseAmt', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['ClientRequest'] = _CLIENTREQUEST
DESCRIPTOR.message_types_by_name['ClientResponse'] = _CLIENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTREQUEST,
  __module__ = 'ClientRequest_pb2'
  # @@protoc_insertion_point(class_scope:ClientRequest.ClientRequest)
  ))
_sym_db.RegisterMessage(ClientRequest)

ClientResponse = _reflection.GeneratedProtocolMessageType('ClientResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTRESPONSE,
  __module__ = 'ClientRequest_pb2'
  # @@protoc_insertion_point(class_scope:ClientRequest.ClientResponse)
  ))
_sym_db.RegisterMessage(ClientResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034io.grpc.comp5325.assignment4B\014COMP5325BankP\001\242\002\002CR'))

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='ClientRequest.Greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=219,
  serialized_end=454,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBalance',
    full_name='ClientRequest.Greeter.GetBalance',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_CLIENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Withdraw',
    full_name='ClientRequest.Greeter.Withdraw',
    index=1,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_CLIENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Deposit',
    full_name='ClientRequest.Greeter.Deposit',
    index=2,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_CLIENTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
