# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ClientRequest_pb2 as ClientRequest__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetBalance = channel.unary_unary(
        '/ClientRequest.Greeter/GetBalance',
        request_serializer=ClientRequest__pb2.ClientRequest.SerializeToString,
        response_deserializer=ClientRequest__pb2.ClientResponse.FromString,
        )
    self.Withdraw = channel.unary_unary(
        '/ClientRequest.Greeter/Withdraw',
        request_serializer=ClientRequest__pb2.ClientRequest.SerializeToString,
        response_deserializer=ClientRequest__pb2.ClientResponse.FromString,
        )
    self.Deposit = channel.unary_unary(
        '/ClientRequest.Greeter/Deposit',
        request_serializer=ClientRequest__pb2.ClientRequest.SerializeToString,
        response_deserializer=ClientRequest__pb2.ClientResponse.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def GetBalance(self, request, context):
    """Sends a action
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Withdraw(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Deposit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalance,
          request_deserializer=ClientRequest__pb2.ClientRequest.FromString,
          response_serializer=ClientRequest__pb2.ClientResponse.SerializeToString,
      ),
      'Withdraw': grpc.unary_unary_rpc_method_handler(
          servicer.Withdraw,
          request_deserializer=ClientRequest__pb2.ClientRequest.FromString,
          response_serializer=ClientRequest__pb2.ClientResponse.SerializeToString,
      ),
      'Deposit': grpc.unary_unary_rpc_method_handler(
          servicer.Deposit,
          request_deserializer=ClientRequest__pb2.ClientRequest.FromString,
          response_serializer=ClientRequest__pb2.ClientResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ClientRequest.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
